remove duplicates
Hiba-alkurd/LeetCodeProblemSolving pull request #3
Opened 2021-01-11 09:09 UTC by Hiba-alkurd

remove duplicates in sorted array using currentIndex to keep track of the current pos and currentDup to keep track of the duplicate value

2021-01-26 20:16 UTC, ziadadeela requested changes

2021-01-26 20:16 UTC, ziadadeela commented on RemoveDuplicates/main.cs
> +        for (int i = 1; i < nums.Length; i++)
ًwhat do you think of my solution 😎?:

> var length = nums.Length;
        if(length == 0){
            return 0;
        }
        var j=1;
        for(var i = 0;i<length-1;i++){
            if(nums[i] != nums[i+1]){
                nums[j] = nums[i+1];
                j++;
            }
        }
        return j;

2021-01-27 06:11 UTC, Hiba-alkurd commented on RemoveDuplicates/main.cs
> +        for (int i = 1; i < nums.Length; i++)
it's interesting, it's faster than 15% of the submissions 👀 but mine is better in memory usage

2021-01-30 14:00 UTC, ziadadeela approved these changes

2021-01-30 14:00 UTC, merged